version: '3.9'

services:
  postgres-db:
    image: postgres:15
    container_name: fresh_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fresh_database
    ports:
      - "5432:5432"
    volumes:
      - fresh_postgres_data:/var/lib/postgresql/data

volumes:
  fresh_postgres_data:
